### ISSUE TITLE
Analyse pipeline does not fail properly

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/cdtn-monolog#53]
Show success despite failure :
```
$ node dist/index.js
 info: Running analysis
 (node:106) UnhandledPromiseRejectionWarning: ResponseError: Response Error
     at IncomingMessage.<anonymous> (/builds/SocialGouv/cdtn-monolog/dist/index.js:51593:25)
     at IncomingMessage.emit (events.js:327:22)
     at endReadableNT (_stream_readable.js:1224:12)
     at processTicksAndRejections (internal/process/task_queues.js:84:21)
 (Use `node --trace-warnings ...` to show where the warning was created)
 (node:106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 (node:106) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 info: 3 batches to insert
 info: Done
``` 

https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-monolog/-/jobs/689213

**Comment by lionelB** [comment]
regarde du coté de fetch
